# 3 Functions, Objects and Libraries

This notebook will introduce how to more broadly employ functions and how to write your own.
<br>
<br>You will be taken through the process of importing libraries of previosuly written functions and introduced to objects and their associated attributes and methods.

---

### 1 Functions

A function is simply a block of code with a name.
<br>
<br>`len()`, which you've used previously, is a function. The block of code it runs computes how long something (a string, or a list) is. The function is applied to the object placed in the brackets after the function name, and in this case the function returns the length of the object.
<br>
<br>The object passed into the function, in brackets, is called the **argument**.

In [1]:
len("hello")

5

Note that writing `len("hello")` is the same thing as writing `5` - just as we can create a variable with `length = 5`, we can use `length = len("hello")`.

It is possible to define new functions in Python.
<br>
<br>Once defined, the code that makes up your function can be run by just referencing the name of the block of code, rather than typing out all of the code. This is useful if you have long stretches of code which need to run lots of times - writing out the same block of code many times is messy, repetitive, time consuming, and may result in errors.
<br>
<br>The code below defines a very simple function called 'calculate_product' which multiplies two numbers together. It takes in two arguments (`a` and `b`), separated by a comma, and returns the output `product`.

In [4]:
def calculate_product(a, b):
    product = a*b
    return product

The syntax is very similar to `if`-`else` statements, and `for` loops.
<br>
<br>`def` tells Python we're about to **def**ine a function.
<br>
<br>`calculate_product` is the name given to this function (block of code).
<br>
<br>`(a, b)`: `a` and `b` are called 'parameters'. These two variables are passed into the function, and can be used by the function.
<br>
<br>`return product` is how we get our calculated value out of the function. Functions are very standalone, so if we don't return anything, all the values that we calculated inside the function will be lost.

We **call** the function with `calculate_product(2, 3)`, i.e. by writing the name of the function, and putting the values for the parameters `a` and `b` in brackets.

**Note:**
>`a` and `b`, when we define the function, are called **parameters** - they do not yet have defined values.
>
>Once given values, e.g. `2` and `3`, when we call the function, `a`and `b` are now called **arguments**.

✏️ Using the `calculate_product()` function, evaluate the value of 59 squared, capture it in a variable, and print the result.

In [6]:
val=calculate_product(59,59)
print(val)

3481


✏️ Write a function that finds the length of the hypotenuse of a right-angled triangle, given both other sides.

*Hint: The function `math.sqrt()` returns the square root of a number. The math library is imported for you below.*

In [7]:
import math #this line lets you use the math.sqrt() function - it will be explained later in this exercise.
def hypotenuse(a,b):
    return math.sqrt(a**2+b**2)

✏️ Try your function out on this triangle:

![a=5,b=12](https://images.saymedia-content.com/.image/t_share/MTg0ODIyMzIyMjQ1NDExOTYw/how-to-use-pythagoras-theorem-to-find-missing-sides-on-right-angled-triangles.jpg)

In [8]:
print(hypotenuse(5,12))

13.0


✏️ The trapezium rule, for numerical integration under a curve, is shown below.
<br>
<br>$$\sum_{i=1}\frac{1}{2}(y_i+y_{i-1})(x_i-x_{i-1})$$
<br>*Note that, for clarity, in this formula `i` is 0-indexed.*
<br>
<br>Write a function which takes in two lists, `x_values` and `y_values`, and returns the area under the curve that they define. You will need to use a for loop with `range()`.
<br>
<Br>*Hint: It is often good practice to attempt a task manually (without a for loop) for the first couple of points, as a starting point. Then, see how you could generalise this to a for loop.*

In [9]:
def numerical_integral(x_values,y_values):
    summation=0
    for i in range(1,len(x_values)):
        summation+=0.5*(y_values[i]+y_values[i-1])*(x_values[i]-x_values[i-1])
    return summation

✏️ Test your function on the x and y values below. You should get an area of 9.5 units.

In [10]:
x_values = [0,1,2,3]
y_values = [0,1,4,9]

print(numerical_integral(x_values,y_values))

9.5


In Python, it is possible to assign multiple variables at the same time, using a comma as a delimiter. This is similar to passing multiple arguments into a function:

In [11]:
a, b = 1, 2
print(a)
print(b)

1
2


Just as it is possible can pass multiple arguments into a function by separating them with commas (`plt.plot(x,y)`), we can **return** multiple values from a function by separating them with commas (`return a, b`).
<br>
<br>When a function returns more than one value, you can assign each value to a variable by separating the variables with commas (`a, b = some_function(c, d)`), like above.

✏️ Write a function which, given $a$, $b$ and $c$, returns **either** the (two) roots of the quadratic equation **or** `None` if there are no real roots.

$$x = \frac{-b\pm\sqrt{b^2-4ac}}{2a}$$

In [21]:
def roots(a,b,c):
    if b**2-4*a*c>=0:
        d=math.sqrt(b**2-4*a*c)/(2*a)
        return -b/(2*a)-d,-b/(2*a)+d
    else:
        return None

✏️ Using the comma notation above, store the two real roots of $y = x^2 + 2x - 100$ in the variables `root_plus` and `root_minus`, and print them both.

In [22]:
root_minus,root_plus=roots(1,2,-100)
print(root_minus,root_plus)

-11.04987562112089 9.04987562112089


---

### 2 Libraries and Importing

It is often the case that the code for a process has already been written by another person at some point in the past. In a lot of these cases, they have then made this code freely available for us, to avoid us having to re-invent the wheel.
<br>
<br>For example, finding the square root of a number is deceptively difficult. Fortunately, programmers much better than you or I have written a function for this. They have put this function in a file called math.py, which came along with Python when it was downloaded onto your computer (e.g. when Anaconda was installed). This file is now called a **library**.
<br>
<br>In order to use the function (called `sqrt()`) in the `math` library, we have to import the library at the start of our code. We import this with the command `import math`.
<br>
<br>Once imported, Python can utilise functions within the `math` library, with the syntax `library.function()`, e.g `math.sqrt()`.
<br>
<br>Alongside the `math` library, the `numpy` library contains lots of mathematical operations you might otherwise have to spend a long time coding yourself and is a commonly imported library for coding in maths and science.

✏️ The `numpy` library contains has a function called `mean()`. Import the `numpy` library, create a list of integers (of your choosing), and use the library function to find the mean of this list.

In [23]:
import numpy as np
integers=list(range(0,50,7))
print(np.mean(integers))

24.5


**Note:**
>It would get a bit wordy writing out 'numpy' every time anything from the library wass required.
>
>The `as` keyword can be used after `import numpy` to import the library under a different (abbreviated) name. For `numpy` this is often taken as `np`.

✏️ Import `numpy` as `np` such that it will work in the code below.

In [24]:
import numpy as np
np.mean([1,2,3,4])

2.5

---

### 3 Objects

In Python, an object is a *thing* which has data associated with it, and which has functions associated with it which can act on it. Almost everything in Python is an object, e.g. lists, strings, etc.
<br>
<br>The data associated with an object are called its attributes. A list's attributes are the items that make it up. For example, the list `[1,2,3,4]`'s attributes are `1`, `2`, `3` and `4`.
<br>
<br>The functions associated with an object, which can act on that object, are called methods. A list has a method (a function associated with it) called `append()`, which acts on it, and adds an item to the end of it.
<br>
<br>A string is also an object. It has attributes, which are the characters which make it up, and methods, which are functions that are associated with it and that can act on it. An example of a method of a string is the function `upper()`, which acts on a string and returns it in upper case.
<br>
<br>Generally, to return an attribute of an object, you use the notation `object.attribute`. Lists are a special case - you use the notation `list[attribute]`.
<br>
<br>Generally, to act on an object with one of its methods, you use the notation `object.method()`. For example, to use the sort method on a list, you write `list.sort()`.
<br>
<br>Some examples of these processes are provided below.

In [25]:
#Create a new list, which we now know is an object.
primes = [2,3,5,7,11]

#Output one of the attributes of the list - the first item.
print(primes[0])

#Output another attribute of the list - the last item.
print(primes[4])

#Apply a method to the list. This method is a function which adds its argument (13) onto the end of the object (the list 'primes').
primes.append(13)

#Print the result.
print(primes)

2
11
[2, 3, 5, 7, 11, 13]


A string object has a method called `count`, which acts on a string, takes a character/letter as an argument, and returns the number of times that character appears in the string.

✏️ Without counting it yourself, how many times does the letter 'a' appear in the string below? You should get 18.
How does the result differ if the argument is altered to 'A'?

In [27]:
string = "Atkins' Physical Chemistry epitomises the benchmark of achievement for a chemistry degree throughout the world. Its broad coverage, concise explanations, and robust mathematical support are clearly presented in an engaging style to furnish students with a solid foundation in the subject."
print(string.count('A'))

1


We saw earlier how we can import functions from libraries. We can also create new types of objects (in addition to just lists and strings) by using templates imported from libraries. For example, `numpy` allows us to create an object called an array, which is very similar to a list.
<br>
<br>We create an object from a library in a similar way to that in which we use a function from a library. Recall that we have to tell Python which library we want to use a function from - so `np.mean()` for the `mean()` function from the `numpy` library. To create an array object from the `numpy` library, we use `np.array()`. In the brackets we can pass arguments for use in creating the object - here we must pass the list we wish to turn into a numpy array.

In [30]:
np_array = np.array([2,4,6,8])

✏️ Use the `print()` function to see what the array defined above looks like.

In [31]:
print(np_array)

[2 4 6 8]


✏️ Create a list object, containing the first 5 prime numbers. Convert your list into a `numpy` array.

In [32]:
lst=[2,3,5,7,11]
array=np.array(lst)

A method of the `numpy` array object is `.max()`, which returns the largest number in the array.

✏️ Use the `max()` method to print the largest prime in your list.

In [33]:
print(np.max(array))

11


`numpy` array objects have an attribute called `size`, which can be accessed with the syntax `array.size`.

✏️ Evaluate the 'size' of your prime number array?

In [34]:
print(array.size)

5


Multiplying a list by a scalar gives a different result to when an array is multiplied by a scalar.

✏️ Create a list of the first 6 integers. Convert this list to a `numpy` array with a different variable name. Multiply both the list and the array by 3 and print the output.

In [35]:
lst1=[1,2,3,4,5,6]
array1=np.array(lst1)
print(6*lst1)
print(6*array1)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
[ 6 12 18 24 30 36]


While both outputs are hopefully logical in their own way, the result for the `numpy` array will likely feel a bit more natural. This is one reason we might use a numpy array over a Python list.

---

### 4 In-Place Operations

When applying functions to things, whether as standalone functions, or as methods, there is quite an important distinction to be made - whether it operates **in-place** or not.
<br>
<br>This means whether it alters the thing it acts on, or returns a new altered copy of it, leaving the original untouched.
<br>
<br>An in-place operation is one which overwrites/changes an existing variable/object. So the `append()` method is an in-place method, since when you run `list.append(value)`, `list` is changed (it has an item added to it).
<br>
<br>Conversely, an operation which is not in-place returns a copy of the existing variable/object, such that if you want to apply the change to the variable/object, you need to reassign it as equal to the result of the operation.
<br>
<br>The `numpy` `reshape()` method is not an in-place operation - `np_array.reshape([2,2])` returns a reshaped array, leaving `np_array` untouched. If you want your reshaping to persist, you need to write `np_array = np_array.reshape([2,2])`.

✏️ Using the `sort()` method of a list, and the `reshape()` method of a numpy array, modify the list A such that it becomes equal to the list B.

*Hint: `sort()` is an in-place operation, while `reshape()` is not.*

In [62]:
A = [5,7,8,5,7,1]
A.sort()
A=np.array(A).reshape([3,2])
B = np.array([[1, 5], [5, 7], [7, 8]])

Check you did this succesfully - the following code should return a 3x2 numpy array with `True` for each value, if your conversions above were correct.

In [63]:
A == B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

---

### 5 Summary

A function is a block of code which can be run by calling the functions's name. A function takes in one or more values, and returns a value.

In [64]:
def divide(a,b):
    return a/b

divide(10,2)

5.0

A library is some code, often written by another party, containing functions and instructions for how to create objects.

In [65]:
import numpy as np

#Use a function from the numpy library.
mean = np.mean([2,4,6]) #4

#Make an object from the numpy library.
array_object = np.array([2,4,6])

An object possesses attributes (data) and methods (functions).

In [66]:
#Make a numpy array object.
np_array = np.array([2,4,6,8])

#An array object has many attributes (properties). One is 'size', which is the size of the array.
np_array.size

#An array object has many methods, which are functions that act on the object.
#One is '.max()', which returns the maximum value in the array.
np_array.max()

#Sometimes a method will take an argument.
#The '.reshape()' method takes as an argument a list, giving the dimensions of a new array to make from your array.
np_array.reshape([2,2])

array([[2, 4],
       [6, 8]])

Not all functions change the identity of the input object. *In-place* operations overwrite the input, while operations that *do not operate in-place* give a new ouput that needs to be assigned to a variable if it is to be referred to in future operations. 

---